config/routes.rb
TwitterForZombies::Application.routes.draw do
  get "welcome/index"

  resources :zombies do
    resources :tweets
    get :decomp, on: :member
    put :custom_decomp, on: :member
  end

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :zombie
  belongs_to :role
end

app/models/brain.rb
class Brain < ActiveRecord::Base
  attr_accessible :flavor, :status, :zombie_id

  belongs_to :zombie
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :assignments
	has_many :zombies, through: :assignments
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  attr_accessible :age, :bio, :name, :decomp
  has_one :brain, dependent: :destroy
  has_many :assignments
  has_many :roles, through: :assignments
  # after_save :decomp_change_notification, if: :decomp_changed?


  def as_json(options = nil)
  	super(options ||
  			{include: :brain, except: [:created_at, :updated_at, :id]})
  end
  
  # private

  # def decomp_change_notification
  # 	ZombieMailer.decomp_change(self).deliver
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.includes(:brain).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id]) 

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :ok }
      format.js
    end
  end

  def decomp
    @zombie = Zombie.find(params[:id])
    if @zombie.decomp == "Dead (again)"
      render json: @zombie.to_json(only: :decomp), 
              status: :unprocessable_entity
    else
      render json: @zombie.to_json(only: :decomp)
    end
  end

  def custom_decomp
    @zombie = Zombie.find(params[:id])
    @zombie.decomp = params[:zombie][:decomp]
    @zombie.save

    respond_to do |format|
      format.js
      format.json { render json: @zombie.to_json(only: :decomp) }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterForZombies</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/index.html.erb
<% @zombies.each do |zombie| %>
	<tr>
		<td><%= zombie.name %></td>
		<td><%= zombie.brain.flavor %></td>
	</tr>
<% end %>

app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :decomp %><br />
    <%= f.text_field :decomp %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/_zombie.html.erb
  <%= div_for zombie do %>
    <%= link_to "Zombie #{zombie.name}", zombie %>
    <div class="actions">
      <%= link_to 'edit', edit_zombie_path(zombie) %>
      <%= link_to 'delete', zombie, method: :delete, remote: true %>
    </div>
  <% end %>  

app/views/zombies/create.js.erb
<% if @zombie.new_record? %>
	$('input#zombie_name').effect('highlight', {color: 'red'});
<% else %>
	$('div#zombies').append("<%= escape_javascript(render @zombie) %>");
	$('div#<%= dom_id(@zombie) %>').effect('highlight');
<% end %>

app/views/zombies/custom_decomp.js.erb
$('#decomp').text('<%= @zombie.decomp %>').effect('highlight', {}, 3000);

<% if @zombie.decomp == "Dead (again)" %>
	$('div#custom_phase').fadeOut();
<% end %>

app/views/zombies/destroy.js.erb
$('#<%= dom_id(@zombie) %>').fadeOut();

app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Listing zombies</h1>
<div id="zombies">
  <%= render @zombies %>
</div>

<%= form_for(Zombie.new, remote: true) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @zombie.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @zombie.bio %>
</p>

<p>
  <b>Age:</b>
  <%= @zombie.age %>
</p>

<strong>Decomposition Phase:</strong>
<span id="decomp"><%= @zombie.decomp %></span>

<div id="custom_phase">
	<%= form_for @zombie, url: custom_decomp_zombie_path(@zombie), remote: true do |f| %>
		<strong>Custom Phase</strong>
		<%= f.text_field :decomp %>
		<%= f.submit "Set" %>
	<% end %>
</div>

<div id="custom_phase2">
  <%= form_for @zombie, url: custom_decomp_zombie_path(@zombie) do |f| %>
    <strong>Custom Phase via JSON</strong>
    <%= f.text_field :decomp %>
    <%= f.submit "Set" %>
  <% end %>
</div>

<div>
<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>
</div>